name: Push OTA Updates

on:
  push:
    branches:
      - main  # This triggers the update every time you push to your main branch

jobs:
  update_android:
    type: update  # Changed from 'build' to 'update'
    params:
      branch: preview # Or 'production', depending on your EAS setup
      message: "Automated update from GitHub Actions"